/**
 * pages/index.js
 * CodeReview.ai — single-page frontend
 *
 * Responsibilities:
 *   - URL input + Analyze button → POST /api/analyze
 *   - Loading, error, and report card states
 *   - Client-side PDF generation via jsPDF (dynamic import)
 */

import { useState } from "react";
import Head from "next/head";

// ---------------------------------------------------------------------------
// Style helpers
// ---------------------------------------------------------------------------

/** Maps a letter grade to a semantic color */
function gradeColor(grade) {
  if (!grade) return "#6b7280";
  const g = grade[0].toUpperCase();
  if (g === "A") return "#16a34a";
  if (g === "B") return "#2563eb";
  if (g === "C") return "#d97706";
  if (g === "D") return "#ea580c";
  return "#dc2626"; // F
}

/** Maps a letter grade to a description */
function gradeDescription(grade) {
  if (!grade) return "";
  const g = grade[0].toUpperCase();
  if (g === "A") return "PERFECT";
  if (g === "B") return "GOOD";
  if (g === "C") return "FAIR";
  if (g === "D") return "POOR";
  return "CRITICAL"; // F
}


/** Maps a numeric score to a progress-bar color */
function scoreColor(score) {
  if (score >= 80) return "#22c55e";
  if (score >= 60) return "#f59e0b";
  return "#ef4444";
}

/** Inline styles for a severity badge */
function severityBadgeStyle(severity) {
  const base = {
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: 4,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    flexShrink: 0,
  };
  if (severity === "high")   return { ...base, background: "#fef2f2", color: "#dc2626" };
  if (severity === "medium") return { ...base, background: "#fffbeb", color: "#d97706" };
  return                            { ...base, background: "#eff6ff", color: "#2563eb" };
}

// ---------------------------------------------------------------------------
// PDF generator (runs browser-only via dynamic import)
// ---------------------------------------------------------------------------

async function generatePDF(report) {
  const { default: jsPDF } = await import("jspdf");
  const doc = new jsPDF();
  const pageWidth = 170; // usable width (20px margins on each side)

  // ── Title ────────────────────────────────────────────────────────────────
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("Code Health Report", 20, 22);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text(`Generated by CodeReview.ai`, 20, 30);
  doc.setTextColor(0);

  // ── Repo meta ────────────────────────────────────────────────────────────
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(`${report.repo}`, 20, 42);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Grade: ${report.grade}   Score: ${report.overall_score}/100   Stars: ${report.stars}`, 20, 50);

  // ── Summary ──────────────────────────────────────────────────────────────
  doc.setFontSize(10);
  const summaryLines = doc.splitTextToSize(report.summary, pageWidth);
  doc.text(summaryLines, 20, 62);

  let y = 62 + summaryLines.length * 5 + 10;

  // ── Top Issues ───────────────────────────────────────────────────────────
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text("Top Issues", 20, y);
  y += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");

  for (const issue of report.top_issues) {
    if (y > 268) { doc.addPage(); y = 20; }

    const header = `[${issue.severity.toUpperCase()}] ${issue.file}  (${issue.category})`;
    const headerLines = doc.splitTextToSize(header, pageWidth);
    doc.setFont("helvetica", "bold");
    doc.text(headerLines, 20, y);
    y += headerLines.length * 5 + 2;

    const issueLines = doc.splitTextToSize(issue.issue, pageWidth - 5);
    doc.setFont("helvetica", "normal");
    doc.text(issueLines, 25, y);
    y += issueLines.length * 5 + 2;

    const fixLines = doc.splitTextToSize(`Fix: ${issue.suggestion}`, pageWidth - 5);
    doc.setTextColor(5, 150, 105); // green
    doc.text(fixLines, 25, y);
    doc.setTextColor(0);
    y += fixLines.length * 5 + 6;
  }

  // ── Strengths ────────────────────────────────────────────────────────────
  if (y > 260) { doc.addPage(); y = 20; }
  y += 4;
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text("Strengths", 20, y);
  y += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");

  for (const s of report.strengths) {
    const lines = doc.splitTextToSize(`• ${s}`, pageWidth);
    doc.text(lines, 20, y);
    y += lines.length * 5 + 3;
  }

  // ── File Scores ──────────────────────────────────────────────────────────
  if (report.file_scores?.length) {
    if (y > 250) { doc.addPage(); y = 20; }
    y += 4;
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.text("File Scores", 20, y);
    y += 8;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");

    for (const f of report.file_scores) {
      doc.text(`${f.file}: ${f.score}/100`, 25, y);
      y += 6;
    }
  }

  // ── Footer ───────────────────────────────────────────────────────────────
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text(`Analyzed: ${report.analyzedAt}`, 20, 285);
  doc.text("https://codereview.ai", 150, 285);

  doc.save(`${report.repo.replace("/", "-")}-health-report.pdf`);
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export default function Home() {
  const [url, setUrl]       = useState("");
  const [loading, setLoading] = useState(false);
  const [report, setReport] = useState(null);
  const [error, setError]   = useState("");

  // ── Analyze handler ────────────────────────────────────────────────────
  const handleAnalyze = async () => {
    const trimmed = url.trim();
    if (!trimmed) return;

    setLoading(true);
    setError("");
    setReport(null);

    try {
      const res = await fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ repoUrl: trimmed }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Analysis failed. Please try again.");
      setReport(data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === "Enter") handleAnalyze();
  };

  const handleDownloadPDF = async () => {
    if (!report) return;
    try {
      await generatePDF(report);
    } catch (err) {
      alert("PDF generation failed: " + err.message);
    }
  };

  // ── Render ────────────────────────────────────────────────────────────
  return (
    <>
      <Head>
        <title>CodeReview.ai — AI Code Health Reports</title>
        <meta
          name="description"
          content="Paste a public GitHub repo link and get an instant AI-powered code health report with grade, score, issues, and suggested fixes."
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style>{`
          *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
          html { scroll-behavior: smooth; }
          body {
            background: #f1f5f9;
            font-family: 'Inter', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            color: #0f172a;
            -webkit-font-smoothing: antialiased;
          }

          /* Input */
          .url-input { transition: border-color 0.15s, box-shadow 0.15s; }
          .url-input:focus {
            outline: none;
            border-color: #6366f1 !important;
            box-shadow: 0 0 0 3px rgba(99,102,241,0.15) !important;
          }

          /* Buttons */
          .btn-primary {
            transition: background 0.15s, transform 0.12s, box-shadow 0.15s;
          }
          .btn-primary:hover:not(:disabled) {
            background: #4f46e5 !important;
            transform: translateY(-1px);
            box-shadow: 0 6px 20px rgba(99,102,241,0.35) !important;
          }
          .btn-primary:active:not(:disabled) { transform: translateY(0); }
          .btn-primary:disabled { opacity: 0.55; cursor: not-allowed; }

          .btn-dark { transition: background 0.15s, transform 0.12s; }
          .btn-dark:hover { background: #334155 !important; transform: translateY(-1px); }

          /* Issue cards */
          .issue-card { transition: border-color 0.15s, box-shadow 0.15s; }
          .issue-card:hover {
            border-color: #cbd5e1 !important;
            box-shadow: 0 2px 12px rgba(0,0,0,0.07) !important;
          }

          /* Animations */
          @keyframes slideUp {
            from { opacity: 0; transform: translateY(20px); }
            to   { opacity: 1; transform: translateY(0); }
          }
          @keyframes spin {
            to { transform: rotate(360deg); }
          }
          @keyframes pulse {
            0%, 100% { opacity: 1; }
            50%       { opacity: 0.6; }
          }

          .report-card   { animation: slideUp 0.4s ease both; }
          .spinner       {
            width: 36px; height: 36px;
            border: 3px solid #e2e8f0;
            border-top-color: #6366f1;
            border-radius: 50%;
            animation: spin 0.75s linear infinite;
            margin: 0 auto 16px;
          }
          .loading-text  { animation: pulse 1.5s ease infinite; }
        `}</style>
      </Head>

      <main style={{ minHeight: "100vh", padding: "56px 20px 80px" }}>
        <div style={{ maxWidth: 800, margin: "0 auto" }}>

          {/* ── Hero ────────────────────────────────────────────────────── */}
          <header style={{ textAlign: "center", marginBottom: 48 }}>
            <div style={{
              display: "inline-flex", alignItems: "center", gap: 10, marginBottom: 14,
            }}>
              <span style={{ fontSize: 32 }}>🔍</span>
              <h1 style={{
                fontSize: 34, fontWeight: 800, letterSpacing: "-0.6px", color: "#0f172a",
              }}>
                CodeReview<span style={{ color: "#6366f1" }}>.ai</span>
              </h1>
            </div>
            <p style={{
              color: "#64748b", fontSize: 16, lineHeight: 1.65,
              maxWidth: 480, margin: "0 auto",
            }}>
              Paste a public GitHub repository URL and get an instant
              AI-powered code health report — with grade, score, and actionable fixes.
            </p>
          </header>

          {/* ── Input bar ───────────────────────────────────────────────── */}
          <div style={{
            background: "#fff",
            borderRadius: 16,
            padding: 8,
            display: "flex",
            gap: 8,
            boxShadow: "0 1px 3px rgba(0,0,0,0.08), 0 8px 24px rgba(0,0,0,0.06)",
            marginBottom: 36,
          }}>
            <input
              id="repo-url-input"
              className="url-input"
              type="url"
              placeholder="https://github.com/owner/repo"
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              onKeyDown={handleKeyDown}
              disabled={loading}
              autoComplete="url"
              style={{
                flex: 1,
                padding: "14px 18px",
                border: "1.5px solid #e2e8f0",
                borderRadius: 10,
                fontSize: 15,
                color: "#0f172a",
                background: "transparent",
                minWidth: 0,
              }}
            />
            <button
              id="analyze-btn"
              className="btn-primary"
              onClick={handleAnalyze}
              disabled={loading || !url.trim()}
              style={{
                padding: "14px 28px",
                background: "#6366f1",
                color: "#fff",
                border: "none",
                borderRadius: 10,
                fontSize: 15,
                fontWeight: 600,
                cursor: "pointer",
                whiteSpace: "nowrap",
                flexShrink: 0,
              }}
            >
              {loading ? "Analyzing…" : "Analyze"}
            </button>
          </div>

          {/* ── Loading state ────────────────────────────────────────────── */}
          {loading && (
            <div style={{ textAlign: "center", padding: "48px 0" }}>
              <div className="spinner" />
              <p className="loading-text" style={{
                fontSize: 15, fontWeight: 600, color: "#475569", marginBottom: 6,
              }}>
                Scanning repository files…
              </p>
              <p style={{ fontSize: 13, color: "#94a3b8" }}>
                Fetching code, calling Groq AI — usually 15–30 seconds
              </p>
            </div>
          )}

          {/* ── Error state ──────────────────────────────────────────────── */}
          {error && !loading && (
            <div style={{
              background: "#fef2f2",
              border: "1.5px solid #fecaca",
              borderRadius: 12,
              padding: "18px 22px",
              display: "flex",
              gap: 14,
              alignItems: "flex-start",
            }}>
              <span style={{ fontSize: 20, flexShrink: 0, lineHeight: 1.4 }}>⚠️</span>
              <div>
                <p style={{ fontWeight: 700, color: "#991b1b", marginBottom: 4, fontSize: 14 }}>
                  Analysis failed
                </p>
                <p style={{ color: "#dc2626", fontSize: 14, lineHeight: 1.5 }}>{error}</p>
              </div>
            </div>
          )}

          {/* ── Report Card ──────────────────────────────────────────────── */}
          {report && !loading && (
            <div className="report-card">

              {/* Header: repo info + grade badge */}
              <section style={{
                background: "#fff",
                borderRadius: 16,
                padding: "28px 32px",
                boxShadow: "0 1px 3px rgba(0,0,0,0.07), 0 8px 24px rgba(0,0,0,0.05)",
                marginBottom: 16,
                display: "flex",
                justifyContent: "space-between",
                alignItems: "flex-start",
                gap: 24,
                flexWrap: "wrap",
              }}>
                {/* Left: meta + score + summary */}
                <div style={{ flex: 1, minWidth: 0 }}>
                  {/* Repo name */}
                  <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 4 }}>
                    <span style={{ fontSize: 20 }}>📁</span>
                    <h2 style={{
                      fontSize: 19, fontWeight: 700, color: "#0f172a",
                      wordBreak: "break-all", lineHeight: 1.3,
                    }}>
                      {report.repo}
                    </h2>
                  </div>
                  <p style={{ color: "#94a3b8", fontSize: 13, marginBottom: 20 }}>
                    ⭐ {report.stars.toLocaleString()} stars
                  </p>

                  {/* Score bar */}
                  <div style={{ marginBottom: 20 }}>
                    <div style={{
                      display: "flex", justifyContent: "space-between",
                      alignItems: "baseline", marginBottom: 7,
                    }}>
                      <span style={{ fontSize: 12, fontWeight: 600, color: "#64748b", letterSpacing: "0.04em", textTransform: "uppercase" }}>
                        Overall Score
                      </span>
                      <span style={{ fontSize: 15, fontWeight: 700, color: scoreColor(report.overall_score) }}>
                        {report.overall_score} / 100
                      </span>
                    </div>
                    <div style={{
                      background: "#f1f5f9", borderRadius: 999, height: 10, overflow: "hidden",
                    }}>
                      <div style={{
                        width: `${report.overall_score}%`,
                        height: "100%",
                        background: scoreColor(report.overall_score),
                        borderRadius: 999,
                        transition: "width 1s cubic-bezier(0.4,0,0.2,1)",
                      }} />
                    </div>
                  </div>

                  {/* AI summary */}
                  <p style={{
                    fontSize: 14, color: "#475569", lineHeight: 1.75,
                    borderLeft: "3px solid #e2e8f0", paddingLeft: 14,
                  }}>
                    {report.summary}
                  </p>
                </div>

                {/* Right: grade badge */}
                <div style={{
                  flexShrink: 0,
                  width: 90,
                  height: 90,
                  borderRadius: 18,
                  background: gradeColor(report.grade) + "18",
                  border: `2px solid ${gradeColor(report.grade)}35`,
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "center",
                  justifyContent: "center",
                  gap: 2,
                }}>
                  <span style={{
                    fontSize: 38, fontWeight: 800, lineHeight: 1,
                    color: gradeColor(report.grade),
                  }}>
                    {report.grade[0]}
                  </span>
                  <span style={{
                    fontSize: 10, fontWeight: 700, letterSpacing: "0.08em",
                    textTransform: "uppercase", color: gradeColor(report.grade), opacity: 0.75,
                  }}>
                    {gradeDescription(report.grade)}
                  </span>
                </div>
              </section>

              {/* Top Issues */}
              <section style={{
                background: "#fff",
                borderRadius: 16,
                padding: "24px 32px",
                boxShadow: "0 1px 3px rgba(0,0,0,0.07), 0 8px 24px rgba(0,0,0,0.05)",
                marginBottom: 16,
              }}>
                <h3 style={{ fontSize: 14, fontWeight: 700, color: "#0f172a", marginBottom: 16, letterSpacing: "0.01em" }}>
                  🐛 Top Issues
                </h3>
                <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
                  {report.top_issues.map((issue, i) => (
                    <div
                      key={i}
                      className="issue-card"
                      style={{
                        padding: "14px 16px",
                        borderRadius: 10,
                        border: "1.5px solid #f1f5f9",
                        background: "#fafafa",
                      }}
                    >
                      {/* Badge row */}
                      <div style={{
                        display: "flex", alignItems: "center", gap: 8,
                        flexWrap: "wrap", marginBottom: 8,
                      }}>
                        <span style={severityBadgeStyle(issue.severity)}>
                          {issue.severity}
                        </span>
                        <code style={{
                          fontSize: 12, fontWeight: 600, color: "#374151",
                          background: "#f8fafc", padding: "2px 7px",
                          borderRadius: 4, border: "1px solid #e2e8f0",
                        }}>
                          {issue.file}
                        </code>
                        {issue.category && (
                          <span style={{
                            fontSize: 11, color: "#94a3b8", padding: "2px 7px",
                            background: "#f1f5f9", borderRadius: 4, fontWeight: 500,
                          }}>
                            {issue.category}
                          </span>
                        )}
                      </div>

                      {/* Issue description */}
                      <p style={{
                        fontSize: 13, color: "#374151", lineHeight: 1.6, marginBottom: 7,
                      }}>
                        {issue.issue}
                      </p>

                      {/* Suggestion */}
                      <p style={{
                        fontSize: 13, color: "#059669", lineHeight: 1.6,
                        display: "flex", gap: 6, alignItems: "flex-start",
                      }}>
                        <span style={{ flexShrink: 0 }}>💡</span>
                        <em>{issue.suggestion}</em>
                      </p>
                    </div>
                  ))}
                </div>
              </section>

              {/* Strengths */}
              <section style={{
                background: "#fff",
                borderRadius: 16,
                padding: "24px 32px",
                boxShadow: "0 1px 3px rgba(0,0,0,0.07), 0 8px 24px rgba(0,0,0,0.05)",
                marginBottom: 16,
              }}>
                <h3 style={{ fontSize: 14, fontWeight: 700, color: "#0f172a", marginBottom: 16 }}>
                  ✅ Strengths
                </h3>
                <ul style={{ listStyle: "none", display: "flex", flexDirection: "column", gap: 10 }}>
                  {report.strengths.map((s, i) => (
                    <li key={i} style={{ display: "flex", gap: 10, alignItems: "flex-start" }}>
                      <span style={{
                        width: 20, height: 20, borderRadius: "50%",
                        background: "#dcfce7", color: "#16a34a",
                        display: "flex", alignItems: "center", justifyContent: "center",
                        fontSize: 12, fontWeight: 700, flexShrink: 0, marginTop: 1,
                      }}>
                        ✓
                      </span>
                      <span style={{ fontSize: 14, color: "#374151", lineHeight: 1.65 }}>{s}</span>
                    </li>
                  ))}
                </ul>
              </section>

              {/* File Scores */}
              {report.file_scores?.length > 0 && (
                <section style={{
                  background: "#fff",
                  borderRadius: 16,
                  padding: "24px 32px",
                  boxShadow: "0 1px 3px rgba(0,0,0,0.07), 0 8px 24px rgba(0,0,0,0.05)",
                  marginBottom: 16,
                }}>
                  <h3 style={{ fontSize: 14, fontWeight: 700, color: "#0f172a", marginBottom: 18 }}>
                    📊 File Scores
                  </h3>
                  <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
                    {report.file_scores.map((f, i) => (
                      <div key={i}>
                        <div style={{
                          display: "flex", justifyContent: "space-between",
                          alignItems: "baseline", marginBottom: 5,
                        }}>
                          <code style={{ fontSize: 12, color: "#475569" }}>{f.file}</code>
                          <span style={{
                            fontSize: 12, fontWeight: 700,
                            color: scoreColor(f.score),
                          }}>
                            {f.score}
                          </span>
                        </div>
                        <div style={{ background: "#f1f5f9", borderRadius: 999, height: 6, overflow: "hidden" }}>
                          <div style={{
                            width: `${f.score}%`, height: "100%",
                            background: scoreColor(f.score), borderRadius: 999,
                          }} />
                        </div>
                      </div>
                    ))}
                  </div>
                </section>
              )}

              {/* Actions */}
              <div style={{ display: "flex", gap: 12, flexWrap: "wrap", marginTop: 4 }}>
                <button
                  id="download-pdf-btn"
                  className="btn-dark"
                  onClick={handleDownloadPDF}
                  style={{
                    padding: "12px 24px",
                    background: "#1e293b",
                    color: "#fff",
                    border: "none",
                    borderRadius: 10,
                    fontSize: 14,
                    fontWeight: 600,
                    cursor: "pointer",
                    display: "flex",
                    alignItems: "center",
                    gap: 8,
                  }}
                >
                  📄 Download PDF Report
                </button>

                <a
                  id="view-on-github-link"
                  href={`https://github.com/${report.repo}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{
                    padding: "12px 24px",
                    background: "#fff",
                    color: "#374151",
                    border: "1.5px solid #e2e8f0",
                    borderRadius: 10,
                    fontSize: 14,
                    fontWeight: 600,
                    textDecoration: "none",
                    display: "flex",
                    alignItems: "center",
                    gap: 8,
                    transition: "border-color 0.15s",
                  }}
                >
                  ↗ View on GitHub
                </a>
              </div>

            </div>
          )}

        </div>
      </main>
    </>
  );
}